# Generated by Django 3.2.7 on 2021-09-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielog',
            name='director',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movielog',
            name='release_day',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movielog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
