# Generated by Django 3.2.7 on 2021-10-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielog', '0002_remove_movielog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
