# Generated by Django 3.2.7 on 2021-10-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielog', '0003_movielog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielog',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
